version: "3"
services:
  elasticsearch:
    build: ./elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elk
    restart: always

  # nginx:
  #   build: ./nginx/
  #   volumes:
  #     - ./nginx/kibana.conf:/etc/nginx/conf.d/kibana.conf
  #   networks:
  #     - elk
  #   ports:
  #     - "5601:5601"
  #   restart: always
  #   depends_on:
  #     - kibana

  kibana:
    build: ./kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    networks:
      - elk
    ports:
      - "5601:5601"
    restart: always
    depends_on:
      - elasticsearch

  logstash:
    build: ./logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/config/grok_patterns.txt:/logstash/config/grok_patterns.txt
    networks:
      - elk
    ports:
      - "5140:5140/udp"
      - "5140:5140/tcp"
    restart: always
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:

networks:
  elk:
